project:
  type: website
  output-dir: docs
  preview:
    port: 4300
    browser: false
  resources: public
website:
  title: "Henrik Korsgaard"
  search: false
  site-path: /about.qmd
  page-footer:
    center:
      - href: https://hci.social/web/@heenrik
        icon: "mastodon"
      - href: mailto:korsgaard@protonmail.com?Subject=I%20saw%20your%20website...
        icon: "envelope"
      - href: https://github.com/henrikkorsgaard
        icon: "github"
      - href: https://twitter.com/heenrik
        icon: "twitter"
      - href: https://www.linkedin.com/in/henrik-korsgaard-77a0831b/
        icon: "linkedin"

  navbar:
    collapse: false
    pinned: false
    title: false
    logo: "/public/images/henrik-transparent.png"
    logo-href: /index.qmd
    left:
      - href: notes.qmd
        text: NOTES
      - href: things.qmd
        text: THINGS
      - href: research.qmd
        text: RESEARCH
      - href: index.qmd
        text: ABOUT
       
format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: false
    email-obfuscation: "javascript"



