project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: false
website:
  title: "Henrik Korsgaard"
  search: false
  page-footer:
    center:
      - href: https://hci.social/web/@heenrik
        icon: "mastodon"
      - href: mailto:korsgaard@protonmail.com?Subject=I%20saw%20your%20website...
        icon: "envelope"
      - href: https://github.com/henrikkorsgaard
        icon: "github"
  navbar:
    collapse: false
    pinned: false
    title: false
    logo: "/public/images/henrik-transparent.png"
    logo-href: /
    left:
      - href: notes.qmd
        text: NOTES
      - href: things.qmd
        text: THINGS
      - href: research.qmd
        text: RESEARCH
      - href: about.qmd
        text: ABOUT
       
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    email-obfuscation: "javascript"



