---
css: /css/research.css
---
<!--
## Research synthesis

- write something on artifact ecologies

-->
## Publications

The following is a list of the publications I have co-authored together with collegues and collaborators. If you find anything interesting or have questions, then feel free to contact me. I welcome any form of discussion of my work.

### Peer-reviewed publications
<div class="pub">
<i class="bi bi-trophy"></i><div class="pub-title">Collectives and their Artifact Ecologies</div>
<author>Henrik Korsgaard, Peter Lyle, Joanna Saad-Sulonen, Clemens Klokmose, Midas Neuwens and Susanne Bødker</author>
<div class="published-at">Proceedings of the ACM on Human-Computer Interaction 6 (CSCW2), 1-26 (2022)</div>
<a href="/public/collective-artifact-ecologies.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3555533" target="new">[doi:10.1145/3555533]</a>
</div>

<div class="pub">
<div class="pub-title">Efficiency and Care in Community-led Initiatives</div> 
<author>Chiara Rossitto, Henrik Korsgaard, Airi Lampinen, Susanne Bødker</author>
<div class="published-at">Proceedings of the ACM on Human-Computer Interaction 5 (CSCW2), 1-27 (2021)</div>
<a href="/public/efficiency-care-community.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3479611" target="new">[doi:10.1145/3479611]</a>
</div>

<div class="pub">
<div class="pub-title">What's the Situation with Situated Visualization? A Survey and Perspectives on Situatedness</div> 
<author>Nathalie Bressa, Henrik Korsgaard, Aurélien Tabard, Steven Houben and Jo Vermeulen</author>
<div class="published-at">IEEE Transactions on Visualization and Computer Graphics 28 (1), 107-117 (2021)</div>
<a href="https://hal.archives-ouvertes.fr/hal-03319648/file/BressaKorsgaardTabardHoubenVermeulen_situatedvis-vis2021.pdf" target="new">[PDF]</a> 
<a href="https://ieeexplore.ieee.org/abstract/document/9552238" target="new">[doi:10.1109/TVCG.2021.3114835]</a>
</div>

<div class="pub">
<div class="pub-title">What’s in a Pattern: A Vocabulary to Articulate Group Routines and Practices</div> 
<author>Susanne Bødker, Henrik Korsgaard and Peter Lyle</author>
<div class="published-at">C&T'21: Proceedings of the 10th International Conference on Communities & Technologies (2021)</div>
<a href="/public/what-is-in-a-pattern.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3461564.3461570" target="new">[doi:110.1145/3461564.3461570]</a>
</div>

<div class="pub">
<div class="pub-title">What’s in an ecology? A review of artifact, communicative, device and information ecologies</div> 
<author>Peter Lyle, Henrik Korsgaard and Susanne Bødker</author>
<div class="published-at">Proceedings of the 11th Nordic Conference on Human-Computer Interaction (2020)</div>
<a href="/public/pdf/artifact-ecology-survey.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3419249.3420185" target="new">[doi:10.1145/3419249.3420185]</a>
</div>

<div class="pub">
<div class="pub-title">Collaborative Writing Across Multiple Artifact Ecologies</div> 
<author>Ida Larsen-Ledet, Henrik Korsgaard and Susanne Bødker</author>
<div class="published-at">Proceedings of the 2020 CHI Conference on Human Factors in Computing Systems(2020)</div>
<a href="/public/pdf/collaborative-writing-artifact-ecologies.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3313831.3376422" target="new">[doi:10.1145/3313831.3376422]</a>
</div>

<div class="pub">
<div class="pub-title">Territorial Functioning in Collaborative Writing</div> 
<author>Ida Larsen-Ledet and Henrik Korsgaard</author>
<div class="published-at">Computer Supported Cooperative Work (CSCW) 28 (3), 391-433 (2019)</div>
<a href="/public/pdf/territorial-functioning-in-collaborative-writing.pdf" target="new">[PDF]</a> 
<a href="https://link.springer.com/article/10.1007/s10606-019-09359-8" target="new">[doi:10.1007/s10606-019-09359-8]</a>
</div>

<div class="pub">
<div class="pub-title">Sketching and Ideation Activities for Situated Visualization Design</div> 
<author>Nathalie Bressa, Kendra Wannamaker, Henrik Korsgaard, Wesley Willett and Jo Vermeulen</author>
<div class="published-at">Proceedings of the 2019 on Designing Interactive Systems Conference (2019)</div>
<a href="/public/pdf/sketching-ideation-situated-visualisation.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3322276.3322326" target="new">[doi:10.1145/3322276.3322326]</a>
</div>

<div class="pub">
<div class="pub-title">Working Across Boundaries in Smart City Research</div> 
<author>Henrik Korsgaard, Sarah-Kristin Theil, Vanessa Thomas and Titiana Ertiö</author>
<div class="published-at">Proceedings of the 19th Annual International Conference on Digital Government Research (2018)</div>
<a href="/public/pdf/working-across-boundaries-smart-city.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3209281.3209315" target="new">[doi:10.1145/3209281.3209315]</a>
</div>

<div class="pub">
<div class="pub-title">PARTICIPATE: Capturing Knowledge in Public Library Activities</div> 
<author>Carla Gröschel, Peter Dalsgaard, Clemens N. Klokmose, Henrik Korsgaard, Eva Eriksson, Raphaëlle Bats, Aurélien Tabard, Alix Ducros and Sofia E. Serholt</author>
<div class="published-at">Extended Abstracts of the 2018 CHI Conference on Human Factors in Computing Systems (2018)</div>
<a href="/public/pdf/Participate2018.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3170427.3188605" target="new">[doi:10.1145/3170427.3188605]</a>
</div>

<div class="pub">
<div class="pub-title">PARTICIPATE: Capturing Knowledge in Public Library Activities</div> 
<author>Carla Gröschel, Peter Dalsgaard, Clemens N. Klokmose, Henrik Korsgaard, Eva Eriksson, Raphaëlle Bats, Aurélien Tabard, Alix Ducros and Sofia E. Serholt</author>
<div class="published-at">Extended Abstracts of the 2018 CHI Conference on Human Factors in Computing Systems (2018)</div>
<a href="/public/pdf/Participate2018.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3170427.3188605" target="new">[doi:10.1145/3170427.3188605]</a>
</div>

<div class="pub">
<div class="pub-title">Proxemic Transitions: Designing Shape-changing Furniture for Informal Meetings</div> 
<author>Jens Emil Grønbæk, Henrik Korsgaard, Marianne Graves Petersen, Morten Henriksen Birk and Peter Gall Krogh</author>
<div class="published-at">Proceedings of the 2017 CHI conference on human factors in computing systems (2017)</div>
<a href="/public/pdf/proxemic-transitions.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3025453.3025487" target="new">[doi:10.1145/3025453.3025487]</a>
</div>

<div class="pub">
<div class="pub-title">Happenstance, Strategies and Tactics: Intrinsic Design in a Volunteer-based Community</div> 
<author>Susanne Bødker, Henrik Korsgaard, Peter Lyle and Joanna Saad-Sulonen</author>
<div class="published-at">Proceedings of the 9th Nordic Conference on Human-Computer Interaction (2016)</div>
<a href="/public/pdf/happenstance-strategies-tactics.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/2971485.2971564" target="new">[doi:10.1145/2971485.2971564]</a>
</div>

<div class="pub">
<i class="bi bi-award"></i><div class="pub-title">'A Farmer, a Place and at least 20 Members': The Development of Artifact Ecologies in Volunteer-based Communities</div>
<author>Susanne Bødker, Henrik Korsgaard and Joanna Saad-Sulonen</author>
<div class="published-at">Proceedings of the 19th ACM Conference on Computer-Supported Cooperative Work & Social Computing</div>
<a href="/public/pdf/development-community-artifact-ecologies.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/3555533" target="new">[doi:10.1145/3555533]</a>
</div>

<div class="pub">
<div class="pub-title">Computational Alternatives in Participatory Design: Putting the T Back in Socio-technical Research</div> 
<author>Henrik Korsgaard, Clemens Nylandsted Klokmose and Susanne Bødker</author>
<div class="published-at">Proceedings of the 14th Participatory Design Conference (2016)</div>
<a href="/public/pdf/computational-alternatives.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/2940299.2940314" target="new">[doi:10.1145/2940299.2940314]</a>
</div>

<div class="pub">
<div class="pub-title">City Bug Report: Urban Prototyping as Participatory Process and Practice</div> 
<author>Henrik Korsgaard and Martin Brynskov</author>
<div class="published-at">Proceedings of the 2nd Media Architecture Biennale Conference (2014)</div>
<a href="/public/pdf/city-bug-report.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/2682884.2682896" target="new">[doi:10.1145/2682884.2682896]</a>
</div>

<div class="pub">
<div class="pub-title">Odenplan: A Media Façade Design Process</div> 
<author>Henrik Korsgaard, Nicolai Brodersen Hansen, Ditte Basballe,Peter Dalsgaard and Kim Halskov</author>
<div class="published-at">Proceedings of the 4th Media Architecture Biennale Conference (2012)</div>
<a href="/public/pdf/odenplan-media-facade-design-process.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/abs/10.1145/2421076.2421081" target="new">[doi:10.1145/2421076.2421081]</a>
</div>

### Book
<div class="pub">
<div class="pub-title">Urban interaction design: Towards city making</div> 
<author>Martin Brynskov, JC Carvajal Bermúdez, Manu Fernandez, Henrik Korsgaard, IJ Mulder, Katarzyna Piskorek, Lea Rekow, Martijn De Waal</author>
<div class="published-at">Urban IxD Booksprint 2014</div>
<a href="/public/pdf/IxD-toward-city-making.pdf" target="new">[PDF]</a>
</div>

### Posters, workshops and position papers

<div class="pub">
<div class="pub-title">2nd Workshop on Studying Technical Mechanisms for Supporting Sharing Communities</div> 
<author>Christina Pakusch, Alexander Boden, Henrik Korsgaard, Myriam Lewkowicz, Gabriela Avram, Susanne Bødker</author>
<div class="published-at">Proceedings of 18th European Conference on Computer-Supported Cooperative Work (2020)</div>
<a href="/public/pdf/studying-technical-mechanisms-II.pdf" target="new">[PDF]</a>
<a href="https://dl.eusset.eu/handle/20.500.12015/4132" target="new">[doi:10.18420/ecscw2021_wsmc01]</a>
</div>

<div class="pub">
<div class="pub-title">Studying Technical Mechanisms for Supporting Sharing Communities</div> 
<author>Henrik Korsgaard, Myriam Lewkowicz, Alexander Boden, Gabriela Avram, Susanne Bødker</author>
<div class="published-at">Proceedings of 18th European Conference on Computer-Supported Cooperative Work (2020)</div>
<a href="/public/pdf/studying-technical-mechanisms.pdf" target="new">[PDF]</a>
<a href="https://dl.eusset.eu/handle/20.500.12015/4059" target="new">[doi:10.18420/ecscw2020_ws01]</a>
</div>

<div class="pub">
<div class="pub-title">Cross-surface: Challenges and Opportunities for 'bring your own device' in the wild</div> 
<author>Steven Houben, Nicolai Marquardt, Jo Vermulen, Johannes Schöning, Clemens Nylandsted Klokmose, Harald Reiterer, Henrik Korsgaard and Mario Schreiner</author>
<div class="published-at">Proceedings of the 2016 CHI Conference Extended Abstracts on Human Factors in Computing Systems</div>
<a href="/public/pdf/CAE-ws2015.pdf" target="new">[PDF]</a>
<a href="https://dl.acm.org/doi/10.1145/2851581.2856490" target="new">[doi:10.1145/2851581.2856490]</a>
</div>


<div class="pub">
<div class="pub-title">A Reality Checklist for Multi-Device Systems in the Wild?</div> 
<author>Henrik Korsgaard, Steven Houben and Clemens Nylandsted Klokmose</author>
<div class="published-at">Proceedings of Cross-Surface 2016: Workshop on Interacting with Multi-Device Ecologies in the Wild</div>
<a href="/public/pdf/Cea3366-houben.pdf" target="new">[PDF]</a>
</div>

<div class="pub">
<div class="pub-title">Composition and mediation in cross-surface interaction</div> 
<author>Henrik Korsgaard and Clemens Nylandsted Klokmose</author>
<div class="published-at">Proceedings of Cross-Surface 2015: Workshop on Cross-surface: Challenges and Opportunities for 'bring your own device' in the wild</div>
<a href="/public/pdf/composition-mediation-cross-surface.pdf" target="new">[PDF]</a>
</div>

<div class="pub">
<div class="pub-title">Towards a concept of community artifact ecology in HCI?</div> 
<author>Joanna Saad-Sulonen and Henrik Korsgaard</author>
<div class="published-at">Workshop contribution at CHI 2015 workshop on Ecologies in HCI research</div>
<a href="/public/pdf/CAE-ws2015.pdf" target="new">[PDF]</a>
</div>

<div class="pub">
<div class="pub-title">Residents’ Democratic engagement in public housing and urban areas–structures, formalities and technologies</div> 
<author>Olav W Bertelsen, Henrik Korsgaard, Ingrid Kuhn, Carolin Schröder, Yngve Sundblad, Kondrad Tollmar</author>
<div class="published-at">Workshop contribution at the 2015 Aarhus 2015 Decennial Conference</div>
<a href="/public/pdf/annual-residents-meetings.pdf" target="new">[PDF]</a>
<a href="https://doi.org/10.7146/aahcc.v1i1.21391" target="new">[doi:10.7146/aahcc.v1i1.21391]</a>
</div>

<div class="pub">
<div class="pub-title">The Annual Resident Meetings How do they work?</div> 
<author>Henrik Korsgaard</author>
<div class="published-at">Workshop on Resident's Democracy at the 2015 Aarhus 2015 Decennial Conference</div>
<a href="/public/pdf/annual-residents-meetings.pdf" target="new">[PDF]</a>
</div>

<div class="pub">
<div class="pub-title">Prototyping a smart city</div> 
<author>Henrik Korsgaard and Martin Brynskov</author>
<div class="published-at">Proceedings of the International Workshop Digital Cities (2013)</div>
<a href="/public/pdf/prototyping-smart-city.pdf" target="new">[PDF]</a> 
</div>

<div class="pub">
<div class="pub-title">Mapping Insights in Creative Processes – Prototyping Integrative Research Designs for Design Research</div> 
<author>Stefan Wiltschnig, Henrik Korsgaard and Peter Dalsgaard</author>
<div class="published-at">DESIRE '11: Procedings of the Second Conference on Creativity and Innovation in Design (2011)</div>
<a href="/public/pdf/mapping-insights-creativity.pdf" target="new">[PDF]</a> 
</div>

<div class="pub">
<div class="pub-title">Integrating laboratory paradigms and ethnographic field studies for advancing analysis of creative processes</div> 
<author>Stefan Wiltschnig, Balder Onarheim, Bo Christensen, Peter Dalsgaard, Henrik Korsgaard Linden J. Ball, Chan Joel, Aaron Houssianm and Anne-Marie Herbert</author>
<div class="published-at">Workshop at DESIRE '11: Procedings of the Second Conference on Creativity and Innovation in Design</div>
<a href="/public/pdf/p365-wiltschnig.pdf" target="new">[PDF]</a>
<a href="https://dl.acm.org/doi/10.1145/2079216.2079272" target="new">[doi:10.1145/2079216.20792726]</a>
</div>


<div class="pub">
<i class="bi bi-trophy"></i><div class="pub-title">Labyrinth Within: Emergence Through Documentation</div> 
<author>Bo Bille and Henrik Korsgaard</author>
<div class="published-at">Proceedings of the 22nd Conference of the Computer-Human Interaction Special Interest Group of Australia on Computer-Human Interaction (2010). Student design competition - online challenge winners.</div>
<a href="/public/pdf/labyrinth-within.pdf" target="new">[PDF]</a> 
<a href="https://dl.acm.org/doi/10.1145/1952222.1952316" target="new">[doi:10.1145/1952222.1952316]</a>
</div>

### Thesis and dissertation

<div class="pub">
</i><div class="pub-title">Toward Place-Centric Computing: Making Place With Technology Together</div> 
<author>Henrik Korsgaard</author>
<div class="published-at">PhD Dissertation, Department of Computer Science, Aarhus University</div>
<a href="/public/pdf/henrik-korsgaard-dissertation-2018-edits.pdf" target="new">[PDF]</a> 
</div>

<div class="pub">
</i><div class="pub-title">Digital Urban Development: Reconceptualising the Smart City as a Design Challenge from an Interaction Design Perspective</div> 
<author>Henrik Korsgaard</author>
<div class="published-at">MSc Thesis, Information Studies and Interaction Design, Aarhus University</div>
<a href="/public/pdf/thesis.pdf" target="new">[PDF]</a> 
</div>