---
title: "Human-Data Interaction Process models"
bibliography:
  - ../references/datascience.bib
  - ../references/hci.bib
  - ../references/general.bib
csl: ../references/apa.csl
citation: 
  type: manuscript
  author: "Henrik Korsgaard"
  version: "0.5"
  issued: "November 2022"

---

In this note I am trying to identify a useful design or process model for Human-Data Interaction. I am not going to claim that HDI _need_ a process model that stand a part from all the others, rather I would argue that we need an integrative one given that HDI  is defined as _"the human manipulation, analysis and sense-making of data."_ Elmqvist (2011). My own interest can be formulated as the challenge of asking good questions to data, or rather, supporting citizens in asking good questions to public data. This involves examining the genesis of the question (information need) and how this interacts with data and the answer, and the process in between. A process model is useful tool in many ways:

Because different disciplines are concerned with different stages and have identified specific challenges and solutions, a process model is a tool for identifying and organize particular challenges, prior work, useful techniques and representations across multiple perspectives. For instance, knowledge discovery concerns itself with the early part of the data analytics process (Fayyad et al. 1996), (visual) analytics with the middle part (Sacha et al. 2014) and information visualization with the presentation (McKenna et al. 2014). None of these areas ignore the other steps, but take particular interest in challenges and solutions for a few primary aspects of the process. 

Process models also describe and organize _work_ and _division of labor_. They say something about what needs to be done when and by whom. This can be between collaborators, specialties, and consequently, the different tools and approaches applied in the process. Some pipeline models, like visualization or machine learning pipelines, describe technical systems, the _flow_ of data and how this is processed once the system have been implemented (Moreland 2013). These can also be considered process models, because the individual components need to be developed and appropriated to the data and task at some point. A _pipeline_ is also an object of design^["Contrary to the more common notion that the output of a knowledge discovery system is simply some fragment of 'knowledge', the output of the knowledge discovery process in a commercial setting, at leaast, wodul more typically be the specification for a knowledge discovery _application_" [@brachman1994process]]. 

Finally, there are a class of process models that deal with the challenge of moving from an articulated need to a solutions through a series of activities that inform both the need and the solution (they all do). While Royces' (1960) initial waterfall model describe a software engineering process, it also grapples with the inherent challenge of dealing with internal and external change in the process. When we start working on a problem, the work changes the articulation and nature of the problem as well as informing the solution (Dewey 1933, Popper 1966, Simon 1973, Rittel and Webber 1973, Schön 1983). While the models do not all take the iterative nature of the work into account, it is fundamental to the process ^["While there may be a nominal canonical order for the above phases, the entire process is iterative and the analyst can move from almost any phase to almost any other at any time."[@brachman1994process]] ^[Henrik: This will challenge any instance where the project is collaborative, see @choi2017characteristics]. Design process models often put a strong emphasis on iteration, agile software engineering similarly, and a lot of the classical models also acknowledge the need for revisiting previous steps (e.g. Li et al. 2016). This is perhaps more about process thinking, sense-making, problem-solution formulation and dialectic reasoning, but this underscores any process. 

The intent is to focus on relevance for human-data interaction, without venturing too far into specific topic areas or entire fields. I will include works that talk about 'information' (needs, seeking, behaviour) and knowledge discovery as well, as it plays a crucial role in motivating HDI and is a part of the outcome of the process -- one want to be informed, know more about something than before and/or get a new perspective. 

## A simple organizing model
The primary focus will be to describe a working model that allow us to identify and organize prior work and important problems for research _and_ application. The model combine multiple models and I will do my best to pay attention to language and differences in the emphasis.


### Information need
The process and model begin with an _information need_. What an information is or can be is an open question and pertains to the individual case. @hofstede1996query argue that it can be that of an organisation or individuals, which suggest that it is already articulated (which may be the case). It is also common that the information need comes from someone else, e.g. a client (find research on this) or someone else in the organization that _needs to know something_ (find research on this). Regardless, an information need is often open and vague, and _"a subjective experience that occurs only in the mind of the person in need and, consequently, is not directly accessible to an observer"_ [@wilson1997information]. Articulating the neeed is therefor inherently challenging and prone to _"I don't know what I'm looking for, but I'll know when I find it"_ [@hofstede1996query]. This means that an information need can start with something puzzeling that needs to be informed before a concret question can be articulated: _"A question well put is half answered"_ [@dewey1933]. This is a dialectical process that involves taking initial steps into the process: _"In fact, a number of the real world analysts we have interviewed strongly emphasized the fact that interation with the data leads to the formation of hypotheses."_ [@brachman1994process] And it is assumed that it is a social process and involves collaborative sensemaking [@paul2010understanding].

There are seveal things to consider here. First, the information need does not come out of the void. It comes from everyday experiences, and often when confronted with something that is puzzling and prompts further inquery. I speculate that when it comes to data-centric information needs, it can be triggered by being exposed to something that is already data-laden:

- When seeing ones electricity bill, one may wonder how the electricity price is determined or how much of the consumption is green energy?
- When experiencing delays in public transport, one may wonder how frequent such delays are or if there is a way to determine where the bus is currently?
- When discussing the climate crisis, one may question how much impact the individual have or what kind of habit changes make the biggest difference?

In the context of HDI, we assume that the user is somewhat motivated to find the information within a structure database or trusted source, and will not just be satisfied by searching the web. This is likely the case in a majority of instances, but we are only interested in supporting the transition from information need to interacting with data. 

So, the first challenge and research theme in HDI interaction should be how people construct their information need -- what is it they need to know? Why? and how does this develop and change througout the process? Is the final outcome an answer to the original information need or did it change?

Important readings here are both within philosophy on reasoning, problem formulation, dialectices etc. and traditional work within information sciences on information need and information seeking behaviour. 

I am not sure this is so relevant in understanding HDI, but for background stuff it might be.


### Data discovery
Once some initial information need is articulated, the user will need to find some data that can inform this. In early work on knowledge discovery it was assumed that this involved consulting familiar data sources, e.g. a database within the organization or similar. For a subset of scenarios, this is also the case today, e.g. within business analysis, analytics, applied data science and modelling. However, with all the available data and the likelyhood that the information needer is not someone working close to a specific domain-specific database, this can easily involve trying to discover data that can inform the question.


People within KDD talk about this step in the same way as they talk about wrangling.

I think that this is more of an issue of identifying and establishing initial ideas about data platforms. 

- consensus data 
- open data
- world et.c 


-- search
-- assessment

-- Reddit study
-- Open data study


### Data exploration

### Data wrangling

### Data analysis

### Data products (outcomes)
- what
- representation
- application



- what are the key elements
- what are the vision
- what are the challenges
- what are the empirical studies
- what are the technical studies
- what are the key challenges



Currently, I am drawing on a basic step model that intends to describe the many places in common data analysis processes people may interact with data:



## Existing models






## KDD

"Data mining and knowledge discovery in databases (KDD) are concerned with extracting models and patterns of interest from large databases." [[KDD-datamining-fayyad-1997.pdf]]

Traditional use of data has been limited to querying a reliable store vial some well-circumscribed application or report generating entity. 
- High degree of familiarity with the data and the processes the data are a product of
- High degree of familiarity with the data model, storage and infrastucture.

While the traditional mode of interaction is satisfactory for a wide-class of well-defined processes, it was not designed to support data exploration and ad hoc querying of the data.

* How can we understand the data?

"These questions become particularly important in the presence of massive data sets since they represent a large body of information that is presumed to be valuable, yet is far
from accessible. The currently available interfaces between humans and machines give little support to navigation, exploration, summarization, or modeling of large databases." [[KDD-datamining-fayyad-1997.pdf]]

Data mining as computer-driven exploration of the data.

Problem in database research is the 

"A problem that has not received much attention in database research is the *query formulation problem*: how can we provide access to data when the user does not know how to describe the goal in terms of a specific query?" [[KDD-datamining-fayyad-1997.pdf]]

## Visualisation pipeline


So, essentially "Making open data more available" is a research challenge that spans the following disciplines

- Databases and datamining: information retrival paradigme  and knowledge 


While each community have addressed the problem within their topic area, the nature of the problems and solutions beyond speciality-oriented solutions, have not been studied.


The different stages, models and areas have some commonalities:

* The interaction is highly dialectical
* Solutions focus (indirectly) on multimodal interation oppertunities on all levels
* It is always a socio-technical challenge where idealized proces models are crystalized into tooling and the advocacy is moving from human-processes, to computer-mediated processes to automation of as many steps as possible.
* 