---
title: "Full CV"
---
Updated February 2023

## Skills and experiences

### Project management

### Communication skills

### Software engineering


## Employment

<table>
<tr><td width="130px"><b>Current</b></td><td><b>Assistant Professor at Department of Computer Science, Aarhus University</b></td></tr>
<tr><td>2017 -- 2020</td><td>Postdoc at Department of Computer Science, Aarhus University</td></tr>
<tr><td>2013 -- 2017</td><td>PhD at Department of Computer Science, Aarhus University</td></tr>
<tr><td>2011 -- 2013</td><td>Project Assistant at AU Smart Cities</td></tr>
<tr><td>2012</td><td>External Lecturer at Department of Aesthetics and Communication</td></tr>
<tr><td>2011 -- 2012</td><td>Research Internship at Center for Advanced Visualisation and Interaction</td></tr>
<tr><td>2010 -- 2012</td><td>Teaching Assistant at Department of Aesthetics and Communication</td></tr>
<tr><td>2006 -- 2007</td><td>Cabinetmaker at Gorm Schierup.</td></tr>
<tr><td>2004 -- 2006</td><td>Cabinetmaker at Brdr. Andersens Møbelsnedkeri</td></tr>
</table>

## Education

<table>
<tr><td width="130px">2013 -- 2017</td><td>PhD at Department of Computer Science, Aarhus University</td></tr>
<tr><td>2010 -- 2013</td><td>MSc in Information Technology at Aarhus University</td></tr>
<tr><td>2007 -- 2010</td><td>BA Information Studies and Multimedia at Aarhus University</td></tr>
<tr><td>2000 -- 2004</td><td>Cabinetmaker apprentice at Brdr. Andersens Møbelsnedkeri</td></tr>
</table>

## Positions and service

<table>
<tr><td width="130px">2022</td><td>Assistant Professor APV Committee at Computer Science, Aarhus University</td></tr>
<tr><td>2020 -- 2023</td><td>Steering Committee Officer: European Society for Socially Embedded Technologies</td></tr>
<tr><td>2021 -- 2022</td><td>Late-Breaking Work Chair at NordiCHI</td></tr>
<tr><td>2021</td><td>Associate Chair CHI 2022 Interaction Beyond the Individual sub-committe</td></tr>

<tr><td>2017 -- 2018</td><td>Member of Postdoc Committee at Computer Science, Aarhus University</td></tr>
<tr><td>2015 -- 2023</td><td>Member of the CS/IT Lab committee at Computer Science, Aarhus University</td></tr>
<tr><td>2015 -- 2017</td><td>Member of PhD Committee at Computer Science, Aarhus University</td></tr>
<tr><td>2015 -- 2016</td><td>Organising Committee member at the 2016 Participatory Design Conference</td></tr>
<tr><td>2015</td><td>Proceedings Chair at the 5th Decennial Aarhus Conference</td></tr>

<tr><td>2013 -- 2014</td><td>PhD at Department of Computer Science, Aarhus University</td></tr>
<tr><td>2012 -- 2013</td><td>Member of the Danish Smart City Network</td></tr>
<tr><td>2021 -- 2022</td><td>Member of Aarhus Open Data work group</td></tr>
<tr><td>2011 -- 2013</td><td>Member of the Smart Aarhus Secretariat</td></tr>
</table>

## Larger research-oriented projects participation
<table>
<tr><td width="130px">2017 -- 2023</td><td>Contributing researcher to the <a href="https://cs.au.dk/research/pages/cio">CIO project</a></td></tr>
<tr><td>2017 -- 2018</td><td>Contributing researcher to the <a href="https://cs.au.dk/research/pages/foundata">FounData</a></td></tr>
<tr><td>2013 -- 2017</td><td>Contributing researcher to <a href="https://pit.au.dk/">Participatory IT centre</a></td></tr>
<tr><td>2013</td><td>Contributing participant to <a href="https://cordis.europa.eu/project/id/325138">EU RADICAL</a></td></tr>
<tr><td>2014</td><td>Application development and contributor to <a href="https://cordis.europa.eu/project/id/645198">Organizity</a></td></tr>
</table>

## Larger research-oriented projects participation
<table>
<tr><td width="130px">2017 -- 2023</td><td>Contributing researcher to the <a href="https://cs.au.dk/research/pages/cio">CIO project</a></td></tr>
<tr><td>2017 -- 2018</td><td>Contributing researcher to the <a href="https://cs.au.dk/research/pages/foundata">FounData</a></td></tr>
<tr><td>2013 -- 2017</td><td>Contributing researcher to <a href="https://pit.au.dk/">Participatory IT centre</a></td></tr>
<tr><td>2013</td><td>Contributing participant to <a href="https://cordis.europa.eu/project/id/325138">EU RADICAL</a></td></tr>
<tr><td>2014</td><td>Application development and contributor to <a href="https://cordis.europa.eu/project/id/645198">Organizity</a></td></tr>
</table>

## Teaching
<table>
<tr><td width="130px">2023</td><td width="500px"><a href="https://www.kursuskatalog.au.dk/en/course/117940/Experimental-System-Development">Experimental System Development</a></td><td width="180px">Approx 120 students</td></tr>
<tr><td >2022</td><td><a href="https://www.kursuskatalog.au.dk/en/course/111403/Experimental-System-Development">Experimental System Development</a></td><td width="100px">Approx 160 students</td></tr>
<tr><td >2021</td><td><a href="https://www.kursuskatalog.au.dk/en/course/104078/Experimental-System-Development">Experimental System Development</a></td><td width="100px">Approx 130 students</td></tr>

<tr><td >2020</td><td><a href="https://kursuskatalog.au.dk/en/course/96707/IT-Product-Design-Project">IT Product Design</a></td><td width="100px">Approx 35 students</td></tr>
<tr><td >2019</td><td><a href="https://kursuskatalog.au.dk/en/course/82760/IT-Product-Design-Project">IT Product Design</a></td><td width="100px">Approx 35 students</td></tr>
<tr><td >2017</td><td><a href="https://kursuskatalog.au.dk/en/course/65359/User-Experience">User Experience (co-lecturing)</a></td><td width="100px">Approx 20 students</td></tr>

<tr><td >2012</td><td><a href="https://kursuskatalog.au.dk/en/course/18859/Avanceret-interaktionsdesign-">Advanced Interactino Design (co-lecturing)</a></td><td width="100px">Approx 20 students</td></tr>

<tr><td >2012</td><td><a href="https://kursuskatalog.au.dk/en/course/65359/User-Experience">Interaction Design BA Project (co-lecturing)</a></td><td width="100px">Approx 20 students</td></tr>
</table>

#### Supervision
Note: Student names removed due to privacy and GDPR.

###### Master thesis
- 1 student (Jan 2017): Proximity Aware System For Control of IoT-Devices, supervisor: Niels Oluf Bouvin, Co-supervisor: Henrik Korsgaard

- 1 student (Jan 2019): Investigating the Relationship Between Volunteer Organization and the Companies That Donate to Them, supervisors: Susanne Bødker & Henrik Korsgaard

- 1 student (Jun 2020): Exploring Moralising Technologies Through Design, supervisors: Henrik Korsgaard & Eve Hoggan

- 3 students (Jun 2020): Value Driven Design Within a Zero Waste Setting, supervisors: Susanne Bødker & Henrik Korsgaard

###### Bachelor thesis
- 3 students (Jun 2018): Place-specific Programming, supervisors: Susanne Bødker & Henrik Korsgaard

- 2 students (Jun 2018): Understanding the Home: A Take on Arti-fact Ecologies, Roles and Shareability, supervisors: Susanne Bødker & Henrik Korsgaard

- 1 student (Aug 2021): The “Black box” Problem of Teaching, supervisors: Eve Hoggan & Henrik Korsgaard

- 2 students (Jun 2022): Increasing Engagement in Utility Usage Among Young People Through Situated Data Visualizations, supervisor: Henrik Korsgaard

#### Examination
<table>
<tr><td width="130px">2022</td><td width="500px"><a href="https://kursuskatalog.au.dk/en/course/114375/Software-Engineering-and-Architecture">Software Engineering and Architecture</a></td><td width="180px">Approx 45 students</td></tr>
<tr><td >2022</td><td><a href="https://kursuskatalog.au.dk/en/course/82769/Project-Work-in-Computer-Science-10-ECTS">Computer Science project</a></td><td width="100px">1 student</td></tr>
<tr><td >2021</td><td><a href="https://kursuskatalog.au.dk/en/course/107637/Software-Engineering-and-Architecture">Software Engineering and Architeture</a></td><td width="100px">Approx 45 students</td></tr>
<tr><td >2020</td><td><a href="https://kursuskatalog.au.dk/en/course/100492/Foundations-of-IT-Product-Design"> Foundations of IT Product Design</a></td><td width="100px">Approx 35 students</td></tr>
<tr><td >2020</td><td><a href="https://kursuskatalog.au.dk/en/course/100494/Physical-Computing">Physical Computing</a></td><td width="100px">Approx 35 students</td></tr>
<tr><td >2019</td><td><a href="https://kursuskatalog.au.dk/en/course/82769/Project-Work-in-Computer-Science-10-ECTS">Computer Science project</a></td><td width="100px">1 student</td></tr>

<tr><td >2019</td><td><a href="https://kursuskatalog.au.dk/en/course/92802/Physical-Computing">Physical computing</a></td><td width="100px">Approx 20 students</td></tr>

<tr><td >2019</td><td><a href="https://kursuskatalog.au.dk/en/course/94679/Building-the-Internet-of-Things-with-P2P-and-Cloud-Computing">Building the IoTs with P2P and Cloud Computing</a></td><td width="100px">Approx 16 students</td></tr>

<tr><td >2018</td><td><a href="https://kursuskatalog.au.dk/en/course/82735/Physical-Computing">Physical computing</a></td><td width="100px">1 student</td></tr>

<tr><td >2017</td><td><a href="https://kursuskatalog.au.dk/en/course/65737/Internet-of-Things-Peer-Networking">IoT/P2P Networking</a></td><td width="100px">Approx 25 students</td></tr>

<tr><td >2015</td><td><a href="https://kursuskatalog.au.dk/en/course/54659/Project-Work-in-Computer-Science-10-ECTS">Computer Science project</a></td><td width="100px">2 students</td></tr>

</table>

#### Pedagogical activities and service
<table>
<tr><td width="130px">2020</td><td>Participated in 2 AU EduIT: Learning Design Workshops, on blended learning and Educational IT</td></tr>
<tr><td >2015 -- 2023</td><td>Member of the lab committee for the Chomsky lab at Computer
Science, Aarhus University</td></tr>
<tr><td >2014</td><td>Participated in organizing and planning the <a href="https://pit.au.dk/events/previous-events/summerpit-2014/phd-summer-school"> PIT summer school</a></td></tr>
<tr><td >2014</td><td>Completed the AU GSST: Introduction to Science Teaching</td></tr>
<tr><td >2011</td><td>Completed the AU Arts: Pedagogical course for Teaching Assistants</td></tr>
<tr><td >2011 -- 2013</td><td>Founding member of the lab committee for the Digital Design lab at Information Studies and Digital Design, Aarhus Universit</td></tr>
</table>

#### Teaching assistant

<table>
<tr><td width="130px">2016</td><td width="500px">IT Product Design Project</td><td width="180px">Approx 40 students</td></tr>
<tr><td >2015</td><td>Experimental Systems Development</td><td>Approx 100 students</td></tr>
<tr><td >2014</td><td>Practical Project in Computer Science</td><td>Approx 50 students</td></tr>
<tr><td >2010 -- 2012</td><td>Interaction Design II</td><td>Approx 20 students</td></tr>
<tr><td >2010</td><td>Introduction to Programming</td><td>Approx 60 students</td></tr>
<tr><td >2010</td><td>Introduction to Object-Oriented Programming</td><td>Approx 60 students</td></tr>
</table>