---
title: "Full Resume"
---
Updated February 2023 -- contact me for further information.

## Skills and experiences

### Design, research and evaluation
I am an expert in interaction design and user experience, and how these two perspectives integrate with software development. I am an experienced qualitative and design researcher across multiple domains from home settings, over education and work, to communities and urban computing. I have facilitated multiple user-centered design processes involving domain studies, workshop facilitation, design meetings and requirement identification and development. I have played a leading role in multiple design projects and used various design formats for stakeholder engagement and alignment. I am familiar with and have applied multiple approches to usability and user experience design evaluation, including various walkthrough methods, heuristic evaluation, focus groups, experience sampling, think aloud, scenario-based evaluation etc. I have experience in teaching interaction design, user experience, evaluation and qualitative approches to design research. 

### Software engineering
I have a broad set of skills in design and software engineering. I developed multiple research prototypes, applications, data-driven projects, etc. applying my interaction design and software developer skills. I have developed smartphone applications from conceptual design to deployment, smaller modules, proof-of-concept systems, network-based systems, data visualisations, and much more, in a broad range of languages. I am familiar with Domain-Driven Design, Test-Driven Development, SCRUM, agile and a large host of devlopment models and principles. I have come to learn that programming languages matter less than a clear vision, well-written requirements and user stories, and the overarching system design (from high-level architecture to specific modules). I have more experience with web-based technologies but have also developed more low-level components, data APIs, and traditional applications. I have experience in teaching practical software development in a project-based course that moves from user needs and requirement identification, to a 3 spring agile process and final evaluation. 

### Project management
I have project management experience from various research and public-private projects, as well as conference organizing events and technical projects. This includes managing deliverables, preparation of technical documentation, developing procedures, managing resources, and expectation alignment in international and national collaborations across multiple stakeholders. In particular, the EU project RADICAL, my work in Smart Aarhus, and organizing conferences have provided valuable lessons and experience in project management, stakeholder alignment, frequent check-ins, coordination, and the importance of appreciative and productive communication.

I am familiar with a large selection of project and project methodologies, from agile methods (e.g. SCRUM) to more formalized approaches like (PRINCE2, LEAN and public IT-process frameworks). I have taught approaches to project management and agile software development for years, including approaches that focus on risk management, quality assurance, estimation challenges, and evaluation. 

My management experiences include managing teaching assistants in my courses. This involves coordination meetings, staffing, coaching on student feedback and classroom management, and developing plans and instructions for them to carry out in their class sessions. In addition, I have supervised 50+ student teams in their course projects, and bachelor and master thesis work. This includes project and code review, helping them scope and prioritize tasks, identifying technical challenges, providing input and advice on their collaboration with external stakeholders, and dealing with various challenges related to deadlines, team dynamics, technical competencies, and communication. 

### Communication skills
I have strong communication skills in both Danish and English. I have experience with scientific communication, technical writing, and developing documentation, tutorials, scenarios, user stories, models, and materials for a wide range of processes and projects. 

I frequently write technical tutorials for multiple levels, e.g. supporting students in deploying with Docker on a VM somewhere in the cloud or developing diagrams and illustrations that can explain complex technical concepts. I have researched collaborative writing, information visualization, and the role various representations (text, sketches, models, user stories) play in software development and elsewhere.

One of my favorite approaches is to combine communication strategies and utilize various representations, from data visualizations to sketches and narratives, to communicate ideas and challenges. A large part of my teaching and supervision is to help students train their academic as well as technical writing.

## Employment

<table>
<tr><td width="130px"><b>Current</b></td><td><b>Assistant Professor at Department of Computer Science, Aarhus University</b></td></tr>
<tr><td>2017 -- 2020</td><td>Postdoc at Department of Computer Science, Aarhus University</td></tr>
<tr><td>2013 -- 2017</td><td>PhD at Department of Computer Science, Aarhus University</td></tr>
<tr><td>2011 -- 2013</td><td>Project Assistant at AU Smart Cities</td></tr>
<tr><td>2012</td><td>External Lecturer at Department of Aesthetics and Communication</td></tr>
<tr><td>2011 -- 2012</td><td>Research Internship at Center for Advanced Visualisation and Interaction</td></tr>
<tr><td>2010 -- 2012</td><td>Teaching Assistant at Department of Aesthetics and Communication</td></tr>
<tr><td>2006 -- 2007</td><td>Cabinetmaker at Gorm Schierup.</td></tr>
<tr><td>2004 -- 2006</td><td>Cabinetmaker at Brdr. Andersens Møbelsnedkeri</td></tr>
</table>

## Education

<table>
<tr><td width="130px">2013 -- 2017</td><td>PhD at Department of Computer Science, Aarhus University</td></tr>
<tr><td>2010 -- 2013</td><td>MSc in Information Technology at Aarhus University</td></tr>
<tr><td>2007 -- 2010</td><td>BA Information Studies and Multimedia at Aarhus University</td></tr>
<tr><td>2000 -- 2004</td><td>Cabinetmaker apprentice at Brdr. Andersens Møbelsnedkeri</td></tr>
<tr><td>1996 -- 1998</td><td>Viby Amtsgymnasium and HF</td></tr>
</table>

## Awards 
<table>
<tr><td width="130px">2022</td><td>CSCW Best Paper Award for <a href="https://dl.acm.org/doi/abs/10.1145/3555533">Collectives and their Artifact Ecologies</a></td></tr>
<tr><td>2016</td><td>CSCW Honorable  Mentions Award for <a href="https://dl.acm.org/doi/abs/10.1145/2818048.2820029">'A Farmer, a Place and at least 20 Members': The Development of Artifact Ecologies in Volunteer-based Communities</a></td></tr>
<tr><td>2010</td><td>Winner of the OzCHI 2010 Student Design Competition</td></tr>
<tr><td>2004</td><td>Bronze medal at the cabinetmaker apprentice exam</td></tr>
</table>

## Positions and service

<table>
<tr><td width="130px">2022</td><td>Assistant Professor APV Committee at Computer Science, Aarhus University</td></tr>
<tr><td>2020 -- 2023</td><td>Steering Committee Officer: European Society for Socially Embedded Technologies</td></tr>
<tr><td>2021 -- 2022</td><td>Late-Breaking Work Chair at NordiCHI</td></tr>
<tr><td>2021</td><td>Associate Chair CHI 2022 Interaction Beyond the Individual sub-committe</td></tr>
<tr><td>2017 -- 2018</td><td>Member of Postdoc Committee at Computer Science, Aarhus University</td></tr>
<tr><td>2015 -- 2023</td><td>Member of the CS/IT Lab committee at Computer Science, Aarhus University</td></tr>
<tr><td>2015 -- 2017</td><td>Member of PhD Committee at Computer Science, Aarhus University</td></tr>
<tr><td>2015 -- 2016</td><td>Organising Committee member at the 2016 Participatory Design Conference</td></tr>
<tr><td>2015</td><td>Proceedings Chair at the 5th Decennial Aarhus Conference</td></tr>
<tr><td>2013 -- 2014</td><td>PhD at Department of Computer Science, Aarhus University</td></tr>
<tr><td>2012 -- 2013</td><td>Member of the Danish Smart City Network</td></tr>
<tr><td>2011 -- 2013</td><td>Member of Aarhus Open Data work group</td></tr>
<tr><td>2011 -- 2013</td><td>Member of the Smart Aarhus Secretariat</td></tr>
</table>

## Larger research-oriented projects participation
<table>
<tr><td width="130px">2017 -- 2023</td><td>Contributing researcher to the <a href="https://cs.au.dk/research/pages/cio">CIO project</a></td></tr>
<tr><td>2017 -- 2018</td><td>Contributing researcher to the <a href="https://cs.au.dk/research/pages/foundata">FounData</a></td></tr>
<tr><td>2013 -- 2017</td><td>Contributing researcher to <a href="https://pit.au.dk/">Participatory IT centre</a></td></tr>
<tr><td>2013</td><td>Contributing participant to <a href="https://cordis.europa.eu/project/id/325138">EU RADICAL</a></td></tr>
<tr><td>2014</td><td>Application development and contributor to <a href="https://cordis.europa.eu/project/id/645198">Organizity</a></td></tr>
</table>

## Teaching
<table>
<tr><td width="130px">2023</td><td width="500px"><a href="https://www.kursuskatalog.au.dk/en/course/117940/Experimental-System-Development">Experimental System Development</a></td><td width="180px">Approx 120 students</td></tr>
<tr><td >2022</td><td><a href="https://www.kursuskatalog.au.dk/en/course/111403/Experimental-System-Development">Experimental System Development</a></td><td width="100px">Approx 160 students</td></tr>
<tr><td >2021</td><td><a href="https://www.kursuskatalog.au.dk/en/course/104078/Experimental-System-Development">Experimental System Development</a></td><td width="100px">Approx 130 students</td></tr>

<tr><td >2020</td><td><a href="https://kursuskatalog.au.dk/en/course/96707/IT-Product-Design-Project">IT Product Design</a></td><td width="100px">Approx 35 students</td></tr>
<tr><td >2019</td><td><a href="https://kursuskatalog.au.dk/en/course/82760/IT-Product-Design-Project">IT Product Design</a></td><td width="100px">Approx 35 students</td></tr>
<tr><td >2017</td><td><a href="https://kursuskatalog.au.dk/en/course/65359/User-Experience">User Experience (co-lecturing)</a></td><td width="100px">Approx 20 students</td></tr>

<tr><td >2012</td><td><a href="https://kursuskatalog.au.dk/en/course/18859/Avanceret-interaktionsdesign-">Advanced Interactino Design (co-lecturing)</a></td><td width="100px">Approx 20 students</td></tr>

<tr><td >2012</td><td><a href="https://kursuskatalog.au.dk/en/course/65359/User-Experience">Interaction Design BA Project (co-lecturing)</a></td><td width="100px">Approx 20 students</td></tr>
</table>

#### Supervision
Note: Student names removed due to privacy and GDPR.

###### Master thesis
- 1 student (Jan 2017): Proximity Aware System For Control of IoT-Devices, supervisor: Niels Oluf Bouvin, Co-supervisor: Henrik Korsgaard

- 1 student (Jan 2019): Investigating the Relationship Between Volunteer Organization and the Companies That Donate to Them, supervisors: Susanne Bødker & Henrik Korsgaard

- 1 student (Jun 2020): Exploring Moralising Technologies Through Design, supervisors: Henrik Korsgaard & Eve Hoggan

- 3 students (Jun 2020): Value Driven Design Within a Zero Waste Setting, supervisors: Susanne Bødker & Henrik Korsgaard

###### Bachelor thesis
- 3 students (Jun 2018): Place-specific Programming, supervisors: Susanne Bødker & Henrik Korsgaard

- 2 students (Jun 2018): Understanding the Home: A Take on Arti-fact Ecologies, Roles and Shareability, supervisors: Susanne Bødker & Henrik Korsgaard

- 1 student (Aug 2021): The “Black box” Problem of Teaching, supervisors: Eve Hoggan & Henrik Korsgaard

- 2 students (Jun 2022): Increasing Engagement in Utility Usage Among Young People Through Situated Data Visualizations, supervisor: Henrik Korsgaard

#### Examination
<table>
<tr><td width="130px">2022</td><td width="500px"><a href="https://kursuskatalog.au.dk/en/course/114375/Software-Engineering-and-Architecture">Software Engineering and Architecture</a></td><td width="180px">Approx 45 students</td></tr>
<tr><td >2022</td><td><a href="https://kursuskatalog.au.dk/en/course/82769/Project-Work-in-Computer-Science-10-ECTS">Computer Science project</a></td><td width="100px">1 student</td></tr>
<tr><td >2021</td><td><a href="https://kursuskatalog.au.dk/en/course/107637/Software-Engineering-and-Architecture">Software Engineering and Architeture</a></td><td width="100px">Approx 45 students</td></tr>
<tr><td >2020</td><td><a href="https://kursuskatalog.au.dk/en/course/100492/Foundations-of-IT-Product-Design"> Foundations of IT Product Design</a></td><td width="100px">Approx 35 students</td></tr>
<tr><td >2020</td><td><a href="https://kursuskatalog.au.dk/en/course/100494/Physical-Computing">Physical Computing</a></td><td width="100px">Approx 35 students</td></tr>
<tr><td >2019</td><td><a href="https://kursuskatalog.au.dk/en/course/82769/Project-Work-in-Computer-Science-10-ECTS">Computer Science project</a></td><td width="100px">1 student</td></tr>

<tr><td >2019</td><td><a href="https://kursuskatalog.au.dk/en/course/92802/Physical-Computing">Physical computing</a></td><td width="100px">Approx 20 students</td></tr>

<tr><td >2019</td><td><a href="https://kursuskatalog.au.dk/en/course/94679/Building-the-Internet-of-Things-with-P2P-and-Cloud-Computing">Building the IoTs with P2P and Cloud Computing</a></td><td width="100px">Approx 16 students</td></tr>

<tr><td >2018</td><td><a href="https://kursuskatalog.au.dk/en/course/82735/Physical-Computing">Physical computing</a></td><td width="100px">1 student</td></tr>

<tr><td >2017</td><td><a href="https://kursuskatalog.au.dk/en/course/65737/Internet-of-Things-Peer-Networking">IoT/P2P Networking</a></td><td width="100px">Approx 25 students</td></tr>

<tr><td >2015</td><td><a href="https://kursuskatalog.au.dk/en/course/54659/Project-Work-in-Computer-Science-10-ECTS">Computer Science project</a></td><td width="100px">2 students</td></tr>

</table>

#### Pedagogical activities and service
<table>
<tr><td width="130px">2020</td><td>Participated in 2 AU EduIT: Learning Design Workshops, on blended learning and Educational IT</td></tr>
<tr><td >2015 -- 2023</td><td>Member of the lab committee for the Chomsky lab at Computer
Science, Aarhus University</td></tr>
<tr><td >2014</td><td>Participated in organizing and planning the <a href="https://pit.au.dk/events/previous-events/summerpit-2014/phd-summer-school"> PIT summer school</a></td></tr>
<tr><td >2014</td><td>Completed the AU GSST: Introduction to Science Teaching</td></tr>
<tr><td >2011</td><td>Completed the AU Arts: Pedagogical course for Teaching Assistants</td></tr>
<tr><td >2011 -- 2013</td><td>Founding member of the lab committee for the Digital Design lab at Information Studies and Digital Design, Aarhus Universit</td></tr>
</table>

#### Teaching assistant

<table>
<tr><td width="130px">2016</td><td width="500px">IT Product Design Project</td><td width="180px">Approx 40 students</td></tr>
<tr><td >2015</td><td>Experimental Systems Development</td><td>Approx 100 students</td></tr>
<tr><td >2014</td><td>Practical Project in Computer Science</td><td>Approx 50 students</td></tr>
<tr><td >2010 -- 2012</td><td>Interaction Design II</td><td>Approx 20 students</td></tr>
<tr><td >2010</td><td>Introduction to Programming</td><td>Approx 60 students</td></tr>
<tr><td >2010</td><td>Introduction to Object-Oriented Programming</td><td>Approx 60 students</td></tr>
</table>